### ISSUE TITLE
Add pMCMC sampler

### ISSUE THREAD

**Issue by johnlees** [mrc-ide/sircovid#20]
@lwhittles has done this here: https://github.com/mrc-ide/sircovid-sandbox/pull/1

I think it's ready for integration into this package

**Comment by lwhittles** [comment]
Great, thanks John! Is there a clever way to do this, or should I just open a new branch in sircovid and copy the code across in to the relevant directories?

**Comment by johnlees** [comment]
I think there are some ways which would preserve the commit history, but they look like they are more complex than it's worth. So I'd just copy over the two new .R files, commit to a new branch, and make a PR here.
With the previous code moved from here we did this too, so it should be ok.

**Comment by lwhittles** [comment]
I have branched off sircovid https://github.com/mrc-ide/sircovid/tree/pmcmc
and integrated the pmcmc and testing scripts from the sandbox https://github.com/mrc-ide/sircovid-sandbox/tree/pmcmc_dev. Just running the build tests now and will create a PR shortly
