### ISSUE TITLE
Adapt the generate_beta function to take two parameters

### ISSUE THREAD

**Issue by MJomaba** [mrc-ide/sircovid#21]
Allow the function to take two parameters instead of one, if the second parameter is not specified, used the current reduction.

**Comment by MJomaba** [comment]
@johnlees

**Comment by johnlees** [comment]
What are the two parameters needed? Currently we have an initial beta, a reduction factor, and a period over which the reduction occurs

**Comment by MJomaba** [comment]
We might everything we want already then. I guess it would be better to be able to specify beta1 and beta2 (so before and after) or beta 1 and then reduction (as it is now).

**Comment by johnlees** [comment]
I can change that. Do you have a sensible beta start and beta end value to use as default?

**Comment by johnlees** [comment]
This function is used in the grid search and MCMC to generate the beta range from a start point. We should generalise this to make it a closure in these cases, so the user can use different parameters for effect and period of reduction
