### ISSUE TITLE
immune escape features

### ISSUE THREAD

**Issue by annecori** [mrc-ide/sircovid#245]
- [x] differential efficacy of vaccine (all 4 rel_* parameters) by variant
- [x] allow infection by one variant before losing natural immunity from the other --> suggest doing this by using "variants" 3 and 4 to model infection with v1 then v2 and v2 then v1 respectively. 
- [x] different duration of infectious period by variant
- [x] different clinical progression by variant
- [x] rate of importation of new variant
- [x] cross-immunity

**Comment by annecori** [comment]
@annecori  working on bullet point 1
@RaphaelS1 working on bullet points 3-5

**Comment by RaphaelS1** [comment]
Point 5 in https://github.com/mrc-ide/sircovid/pull/252
Will start 3 next

**Comment by RaphaelS1** [comment]
Point 3 in https://github.com/mrc-ide/sircovid/pull/256/
Will start 4 next

**Comment by RaphaelS1** [comment]
Point 4 in https://github.com/mrc-ide/sircovid/pull/261 - Needs tests
Starting 2

**Comment by RaphaelS1** [comment]
PR https://github.com/mrc-ide/sircovid/pull/261 is finished, all tests passing and ready to review.
Point 2 in https://github.com/mrc-ide/sircovid/pull/262

**Comment by RaphaelS1** [comment]
Final point in https://github.com/mrc-ide/sircovid/pull/273

**Comment by RaphaelS1** [comment]
Shall we close this @annecori  ?
