### ISSUE TITLE
Write a model with alternative hospitalisation structure

### ISSUE THREAD

**Issue by MJomaba** [mrc-ide/sircovid#26]
We are currently working on deciding what is the best model structure to capture the flow of hospitalised patients. Once we have decided on this, we can create an amended version of the existing model to be used in the package. @MJomaba

**Comment by MJomaba** [comment]
Shall we close this one?

**Comment by johnlees** [comment]
Was keeping it open due to needing tests, but that's now #43 so yes I think so!
