### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by OJWatson** [mrc-ide/sircovid#31]
Rich just sent me the following issue when testing the grid search through the new orderly task:

```
[17:34] Fitzjohn, Richard G
    
^[[BError in getGlobalsAndPackages(expr, envir = envir, tweak = tweakExpression,  : 
  The total size of the 7 globals that need to be exported for the future expression (‘{; ...future.f.env <- environment(...future.f); if (!is.null(...future.f.env$`~`)) {; if (is_bad_rlang_tilde(...future.f.env$`~`)) {; ...future.f.env$`~` <- base::`~`; }; ...; .out; }); }’) is 6.31 GiB. This exceeds the maximum allowed size of 500.00 MiB (option 'future.globals.maxSize'). The three largest globals are ‘...future.x_ii’ (6.31 GiB of class ‘list’), ‘is_bad_rlang_tilde’ (15.05 KiB of class ‘function’) and ‘...future.map’ (6.61 KiB of class ‘function’).
Calls: tryCatch ... SequentialFuture -> UniprocessFuture -> getGlobalsAndPackages
```

We are clearly hitting some memory issues - I tried running it locally and it gets very close to 16Gb. Something is clearly an issue in future or somewhere. Posting here till we figure out what

**Comment by OJWatson** [comment]
This is with a beta start date grid of 697 pairs...

**Comment by johnlees** [comment]
If we put the log likelihood extraction in the pmap function perhaps? I guess the problem is using `X` as a future, which will be large.

If that doesn't work, we can rewrite. Is there an alternative standard multiprocessing package in R?

**Comment by johnlees** [comment]
@OJWatson If you get a chance, could you try the code on the `grid-memory` branch (f4d29e7b5cf24df271ee9405d78f25263d395382) and see if that uses less memory on your local run?
