### ISSUE TITLE
Plot daily death counts from sample grid results instead of cumulative deaths

### ISSUE THREAD

**Issue by edknock** [mrc-ide/sircovid#35]
When (what == "Deaths") in plot.sample_grid_search, we want to plot daily death counts, instead of cumulative deaths (as it is now). Makes sense as we are fitting to daily death counts. Plots will also be easier to interpret.

**Comment by lwhittles** [comment]
Happy to take a look at this if you like @edknock ?

**Comment by edknock** [comment]
Thanks @lwhittles! Can we make sure to scale the plotted data points using pars_obs$phi_death please. Basically in the same way that happens for ICU.
