### ISSUE TITLE
Simulation for whole of UK is broken

### ISSUE THREAD

**Issue by pabloperguz** [mrc-ide/sircovid#365]
Simulating for all of the UK is broken. At the moment, the Rt calculation in `sircovid::lancelot_Rt_trajectories` returns the following error message:
`Error in findInterval(x, critical) : `
`  'vec' must be sorted non-decreasingly and not contain NAs`

**Comment by richfitz** [comment]
I don't think this one should be assigned to me, this is not code I know anything about

**Comment by pabloperguz** [comment]
Fixed a while ago by @epiyasin (thanks!)
