### ISSUE TITLE
Add tests for new hospitalisation model

### ISSUE THREAD

**Issue by johnlees** [mrc-ide/sircovid#43]
Similar tests to those in `test-model.R`

**Comment by edknock** [comment]
Have a version of tests here https://github.com/mrc-ide/sircovid/blob/test_new_hospital_model/tests/testthat/test-new-hospital-model.R

Expect they may need to be adapted for this PR https://github.com/mrc-ide/sircovid/pull/49

**Comment by johnlees** [comment]
These look good. I think we should merge both #49 and #50 then take another look to see if they need updating (but I think it should be minor)
