### ISSUE TITLE
pmcmc start_date issue

### ISSUE THREAD

**Issue by lwhittles** [mrc-ide/sircovid#51]
Since the pmcmc has been updated to deal with time-varying beta, there is an issue with how it is dealing with the start_date parameter.

The input date
`pars_init$date`
is initially converted to the number of days before the first date in the fitting data
https://github.com/mrc-ide/sircovid/blob/636abde9b11971ed4ed1ad2e58324209e75e2f4a/R/pmcmc.R#L226

However, when this is passed to the likelihood function, it is converted back to a date with reference to `model_start_date`
https://github.com/mrc-ide/sircovid/blob/636abde9b11971ed4ed1ad2e58324209e75e2f4a/R/pmcmc.R#L363
Here `model_start_date` is passed directly from the pmcmc() arguments, and is set by default to `2020-02-02`
https://github.com/mrc-ide/sircovid/blob/636abde9b11971ed4ed1ad2e58324209e75e2f4a/R/pmcmc.R#L88

This causes an issue when passing, say 
`pars_init$start_date = as.Date('2020-02-01)`
where 
`data$date[1]` is `2020-03-16`
which becomes 
`curr_pars['start_date'] = 44` on line 226
but is then converted to 
`start_date = '2020-03-17'` 
within the likelihood function (i.e 44 days after `model_start_date`)
and throws an error in the particle filter due to being in advance of the first date in the data.

Is `model_start_date` different from the start_date we are trying to fit here?

**Comment by johnlees** [comment]
Closed in #60
